#!/usr/bin/env bash
# Configure nginx to run as nginx user on port 8080
useradd -s /sbin/nologin nginx 2>/dev/null
sed -i 's/^user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80/listen [::]:8080/g' /etc/nginx/sites-available/default
service nginx restart
