#!/usr/bin/env bash
# Configures nginx with custom HTTP response header
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
sed -i '/server_name _;/a\\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
service nginx restart
